services:
  semantickernel-plugins:
    build:
      context: ../semantickernel-plugins
      dockerfile: ./Dockerfile
    ports:
      - "5155:5155"
    environment:
      - ASPNETCORE_URLS=http://+:5155